@startuml ugc
!theme cerulean-outline

skinparam sequence {
    MaxMessageSize 2
    MessageAlign center
}

actor "Пользователь" as user 
actor "Администратор" as admin
actor "Аналитик" as analyst 

component "Admin-сервис" as admin_panel
component "Auth-сервис" as auth_service

node "Content" {
    component "Content-Service" as content_service
    component "Content ETL" as content_etl 
    database "ElasticSearch" as elastic
    database "Movie-db" as movie_db 
}

node "Analyze" as analyze_etl_process {
    database "OLAP" as olap
    component "Data analyze ETL" as analyze_etl
    component "Analyze-Service" as analyze_api
    database "Kafka" as kafka
}

user --> analyze_api
analyze_api --> analyze_api: Проверка токена
analyze_api --> kafka: Запись событий пользователей

analyze_etl --> kafka
analyze_etl --> olap 
analyst --> olap: Анализ данных

user --> content_service
content_service --> content_service: Проверка токена
content_service --> elastic
admin --> admin_panel: Редактирование данных
admin_panel --> movie_db 

content_etl --> movie_db 
content_etl --> elastic 
@enduml
