version: '3.5'

services:
  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica
    restart: always
    volumes:
      - vertica-data:/user-data
    ports:
      - "5433:5433"

volumes:
  vertica-data: